name: YC Job Collector

on:
  workflow_dispatch:

jobs:
  collect-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Scraper
        run: node scraper.js

      - name: Upload To Supabase
        run: node upload.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}